### PR TITLE
Update dimod to 0.10.11

### PR DESCRIPTION
**Pull request by arcondello**
Should fix the dimod doctest failures.

### CODE REVIEW

**Review by randomir — APPROVED** [review]
Doctest fix looks good, but we should probably first drop py36 (in a separate PR?)

**Comment by arcondello** [comment]
since dimod 0.10.11 doesn't support Python 3.6 this PR is blocked until we do. An alternative would be to conditionally install dimod by python version but IMO it makes sense to just drop the 3.6 and rebase.

**Comment by arcondello** [comment]
> Doctest fix looks good, but we should probably first drop py36 (in a separate PR?)

haha, jinx

**Comment by randomir** [comment]
Just 14s... :laughing: 

image

**Pull request merged**
