### PR TITLE
Unified docs: replace dir copies with symlinks

### PR DESCRIPTION
**Pull request by JoelPasvolsky**
@arcondello, would you please update submodules for this step, so I can clear some of the build warnings, I'll work on fixing the rest on a cleaner build.

### CODE REVIEW

**Comment by JoelPasvolsky** [comment]
These failures are penaltymodel version mismatches, not related to my changes

**Comment by arcondello** [comment]
Do we want to merge this simultaneously with the new tagged versions of the various projects? Otherwise won't the docs be broken?

**Comment by JoelPasvolsky** [comment]
Yes

**Comment by arcondello** [comment]
Was that a response to the first or second question?

**Comment by JoelPasvolsky** [comment]
Okay, I updated the submodules

**Pull request merged**
