### PR TITLE
Add pyqubo to setup.py

### PR DESCRIPTION
**Pull request by kotarotanahashi**
Added pyqubo to setup.py

@randomir @arcondello It would be great If you could add `pyqubo` to ocean's dependencies.

### CODE REVIEW

**Comment by arcondello** [comment]
Hi @kotarotanahashi , sorry to be so late in replying to you, we would really like to merge pyqubo into the sdk! One thing that is preventing us from merging at this time is the convention `Qubit` to describe a {0, 1} variable, which might be confusing to Ocean users. In Ocean we use the convention `Binary` for {0,1} and `Spin` for {-1,+1}.

**Comment by kotarotanahashi** [comment]
@arcondello No problem! 
> the convention `Qubit` to describe a {0, 1} variable, which might be confusing to Ocean users
I can replace `Qubit` with `Binary`. Does that work? If you notice more problems, please let me know!

**Comment by arcondello** [comment]
Yes I think that would do it, thanks!

**Comment by kotarotanahashi** [comment]
@arcondello I replaced the class name "Qbit" to "Binary" not to confuse ocean users.
Thank you for pointing out the issue.
https://github.com/recruit-communications/pyqubo/releases/tag/0.2.0

**Comment by arcondello** [comment]
Great! If you could just update the PR for the new version we'll merge. Or we can do it on our side

**Comment by kotarotanahashi** [comment]
Hi, @arcondello , I updated the version of pyqubo, and resolved a conflict. It seems that we are ready to merge it.

**Pull request merged**
