### PR TITLE
Add clang

### PR DESCRIPTION
**Pull request by JoelPasvolsky**
Closes https://github.com/dwavesystems/dwave-ocean-sdk/issues/89

### CODE REVIEW

**Comment by arcondello** [comment]
Closes #90

**Review by arcondello — APPROVED** [review]

**Comment by randomir** [comment]
How about we merge #90?

**Comment by arcondello** [comment]
I am fine with either, I was not sure if @JoelPasvolsky preferred this one for some reason.

**Comment by JoelPasvolsky** [comment]
I just saw https://github.com/dwavesystems/dwave-ocean-sdk/issues/89 and decided to do the work on it, I did not know about https://github.com/dwavesystems/dwave-ocean-sdk/pull/90

**Comment by arcondello** [comment]
Ok, shall we proceed with #90 then?

**Comment by randomir** [comment]
That would be my preference.

**Pull request closed without merging**
