### PR TITLE
Update PyQUBO version to 1.3.1

### PR DESCRIPTION
**Pull request by kotarotanahashi**
PyQUBO version 1.3.0 is released. This version is compatible with dimod 0.11.x.
https://github.com/recruit-communications/pyqubo/releases/tag/1.3.0

### CODE REVIEW

**Comment by kotarotanahashi** [comment]
@arcondello We recently released PyQUBO 1.3.0 which supports dimod 0.11.x. I would appreciate it if you could review it.

**Comment by arcondello** [comment]
Hi @kotarotanahashi we actually just released dimod 0.12.0 today. I believe support should be straightforward.

**Comment by kotarotanahashi** [comment]
@arcondello I see it! I'll update PyQUBO to support the latest version of dimod. Thank you.

**Comment by kotarotanahashi** [comment]
@arcondello I updated PyQUBO to support dimod 0.12.x. in the latest PyQUBO v1.3.1 (https://github.com/recruit-communications/pyqubo/releases/tag/1.3.1) Thank you!

**Pull request merged**
