### PR TITLE
Update pyqubo version to 1.0.6

### PR DESCRIPTION
**Pull request by kotarotanahashi**
- Update PyQUBO version to 1.0.6
- In the new version, the backend of PyQUBO is implemented in C++, and the execution time is 1000 times faster than the previous version.

### CODE REVIEW

**Comment by arcondello** [comment]
Hi @kotarotanahashi , are there other backwards compatibility breaks we should know about?

**Comment by kotarotanahashi** [comment]
Hi @arcondello.
I change the interface of some methods in PyQUBO. Do you need the list of changes?
Compatibility with other ocean packages hasn’t changed this time.

**Comment by kotarotanahashi** [comment]
@arcondello 
> are there other backwards compatibility breaks we should know about?

Main changes made in this version is described in the following release page.
https://github.com/recruit-communications/pyqubo/releases/tag/1.0.0

**Comment by arcondello** [comment]
Hi @kotarotanahashi , thanks for the update. We were trying to determine if this change should increment the major version of our sdk. I talked with @randomir about it, and I think it is OK for this to just increment the minor version. Thanks for the PR!

**Comment by kotarotanahashi** [comment]
@arcondello 
> I think it is OK for this to just increment the minor version

I see! Thank you for the review.

**Pull request merged**
