### PR TITLE
Add a banner to the README

### PR DESCRIPTION
**Pull request by arcondello**
I also added badges for docs and python versions, because why not.

Preview in light mode
----------------------------
image

Preview in dark mode
----------------------------
image

### CODE REVIEW

**Review by hhtong — APPROVED** [review]
That was fast!

**Review by randomir — COMMENTED** [review]
We need a nicer banner.

Ideally, a new Ocean logo to start with, but at the very least we need to fix the SDK suffix. It simply does not fit next to Ocean text.  I would make it (1) lighter, (2) thinner, (3) increase font size _or_ use lowercase "sdk".

The meaningless curves at the bottom actually are apt here, as one can imagine they represent an ocean, I guess.

**Comment by arcondello** [comment]
From Aaron:
image

**Comment by randomir** [comment]
@JoelPasvolsky, that's a great point. Do we? I don't think we do.

**Comment by arcondello** [comment]
Version with only ocean:

image

image

**Review by JoelPasvolsky — APPROVED** [review]

**Review by randomir — APPROVED** [review]

**Pull request merged**
