### PR TITLE
Workflow graphic

### PR DESCRIPTION
**Pull request by JoelPasvolsky**
The current graphic is an MS Paint placeholder that served for a good couple of years so it is with some sadness that I propose retiring it. Big thanks to Michael for the new graphic.

### CODE REVIEW

**Review by arcondello — APPROVED** [review]

**Comment by thisac** [comment]
Looks good! The older image looks a bit squashed in the docs for me, though. Should this be fixed as well?

image

**Comment by JoelPasvolsky** [comment]
> Looks good! The older image looks a bit squashed in the docs for me, though. Will this be fixed as well?
> 
It's looking unsquashed for me. 
image

**Comment by JoelPasvolsky** [comment]
> Could we "retire" raster graphics in favor of vector graphics, and use an SVG here instead?

Addressed by [this commit](https://github.com/dwavesystems/dwave-ocean-sdk/pull/281/commits/2a6580295d84c63756bf80a7e666192e29f63c4b)

**Comment by randomir** [comment]
> > Could we "retire" raster graphics in favor of vector graphics, and use an SVG here instead?
> 
> Addressed by [this commit](https://github.com/dwavesystems/dwave-ocean-sdk/pull/281/commits/2a6580295d84c63756bf80a7e666192e29f63c4b)

Lovely! Thanks!

**Review by randomir — APPROVED** [review]

**Review by thisac — APPROVED** [review]

**Pull request merged**
